spring:
  application:
    name:
      auth-service
  datasource:
    url: jdbc:postgresql://192.168.39.27:30432/authdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
app:
  jwt:
    private-key-path: ${JWT_PRIVATE_KEY_PATH:src/main/resources/keys/private.pem}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:src/main/resources/keys/public.pem}
    access-token-expiry: 60
    refresh-token-expiry: 120
logging:
  level:
    org.flywaydb: DEBUG