apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJrb3JuaXlrb20iLCJwYXNzd29yZCI6ImdocF9IVUFUZTJRU1lLajcxYWZYcWtCV3lIM3ljMEhGQzE0QVhWSmwiLCJlbWFpbCI6Imtvcm5peWtvbUBnbWFpbC5jb20iLCJhdXRoIjoiYTI5eWJtbDVhMjl0T21kb2NGOUlWVUZVWlRKUlUxbExhamN4WVdaWWNXdENWM2xJTTNsak1FaEdRekUwUVZoV1Ntdz0ifX19
kind: Secret
metadata:
  name: ghcr-secret
  namespace: webvetcare
type: kubernetes.io/dockerconfigjson
