[versions]
kotlin = "2.3.20"
springBoot = "4.1.0"
springDependencyManagement = "1.1.7"
springCloudBom = "2025.1.1"
springCloudDependencyManagement = "2025.1.1"
commonsCodec = "1.21.0"
testcontainers = "1.21.4"
java = "17"

[libraries]
springCloudConfigServer = { module = "org.springframework.cloud:spring-cloud-config-server" }
springCloudConfigClient = { module = "org.springframework.cloud:spring-cloud-starter-config" }
springCloudLoadBalancer = { module = "org.springframework.cloud:spring-cloud-starter-loadbalancer" }
springCloudGateway = { module = "org.springframework.cloud:spring-cloud-gateway-server-webflux" }
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloudBom" }
springBootStarterOauth2ResourceServer = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server", version.ref = "springBoot" }
springSecurityOauth2ResourceServer = { module = "org.springframework.security:spring-security-oauth2-resource-server" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
jacksonModuleKotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
kotlinTestJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web" }
springBootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBootStarterDataJpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }
springBootStarterWebflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springSecurityCrypto = { module = "org.springframework.security:spring-security-crypto" }
springSecurityOauth2Jose = { module = "org.springframework.security:spring-security-oauth2-jose" }
flywayCore = { module = "org.flywaydb:flyway-core" }
flywayDatabasePostgresql = { module = "org.flywaydb:flyway-database-postgresql" }
postgresql = { module = "org.postgresql:postgresql" }
commonsCodec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
testcontainersPostgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainersJunitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "6.3.0" }

[plugins]
kotlinPluginSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlinPluginJpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }