apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: webvetcare
spec:
  selector:
    app: config
  type: ClusterIP
  ports:
    - port: 9994
      targetPort: 9994
      protocol: TCP
      name: http