apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoia29ybml5a29tIiwicGFzc3dvcmQiOiJnaHBfM1loYzVTeDlJZE4wMzdkYVVnQ2R1R01wNmhpajA4MVptbzlsIiwiZW1haWwiOiJrb3JuaXlrb21AZ21haWwuY29tIiwiYXV0aCI6ImEyOXlibWw1YTI5dE9tZG9jRjh6V1doak5WTjRPVWxrVGpBek4yUmhWV2REWkhWSFRYQTJhR2xxTURneFdtMXZPV3c9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-06-15T23:04:01Z"
  name: ghcr-secret
  namespace: webvetcare
  resourceVersion: "980"
  uid: deb32d24-eec7-4e96-bd83-361ebc257d70
type: kubernetes.io/dockerconfigjson
