apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoia29ybml5a29tIiwicGFzc3dvcmQiOiJnaHBfMENQcExLM3JXMG8yWWlMVnZyOGR2T0xKNHp3QWRBMTNoSVZQIiwiZW1haWwiOiJrb3JuaXlrb21AZ21haWwuY29tIiwiYXV0aCI6ImEyOXlibWw1YTI5dE9tZG9jRjh3UTFCd1RFc3pjbGN3YnpKWmFVeFdkbkk0WkhaUFRFbzBlbmRCWkVFeE0yaEpWbEE9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-03-30T14:15:43Z"
  name: ghcr-secret
  namespace: webvetcare
  resourceVersion: "1069"
  uid: 0de4415d-77c0-413d-9d90-4fa10e3615c1
type: kubernetes.io/dockerconfigjson
