apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoia29ybml5a29tIiwicGFzc3dvcmQiOiJnaHBfQWUxSWdVMEJhUHNaQVJia2h0UnRBc2I5R2dFMXZnM2FOeGRSIiwiZW1haWwiOiJrb3JuaXlrb21AZ21haWwuY29tIiwiYXV0aCI6ImEyOXlibWw1YTI5dE9tZG9jRjlCWlRGSloxVXdRbUZRYzFwQlVtSnJhSFJTZEVGellqbEhaMFV4ZG1jellVNTRaRkk9In19fQ==
kind: Secret
metadata:
  name: ghcr-secret
  namespace: webvetcare
type: kubernetes.io/dockerconfigjson
