apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webvetcare

resources:
  - namespace.yaml

  - gateway/deployment.yaml
  - gateway/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - auth-service/jwt-keys-sealed.yaml

  - auth-service/postgres/postgres-deployment.yaml
  - auth-service/postgres/postgres-service-clusterip.yaml
  - auth-service/postgres/postgres-service-nodeport.yaml

  - user-service/deployment.yaml
  - user-service/service.yaml

  - user-service/postgres/postgres-deployment.yaml
  - user-service/postgres/postgres-service-clusterip.yaml
  - user-service/postgres/postgres-service-nodeport.yaml

  - ingress.yaml