apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webvetcare

resources:
  - namespace.yaml

  - ghcr-secret.yaml

  - config/service.yml
  - config/deployment.yml

  - gateway/deployment.yaml
  - gateway/service.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - auth-service/jwt-keys-sealed.yaml

  - auth-service/postgres/stateful-set.yaml
  - auth-service/postgres/service.yaml

  - user-service/deployment.yaml
  - user-service/service.yaml

  - user-service/postgres/stateful-set.yaml
  - user-service/postgres/service.yaml

  - ingress.yaml