apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: gateway
          image: ghcr.io/korniykom/webvetcare-gateway:0.0.1-snapshot
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_URI
              value: "http://config:9994"
            - name: AUTH_SERVICE_URL
              value: http://auth-service:9991
            - name: USER_SERVICE_URL
              value: http://user-service:9992
            - name: JWKS_URI
              value: http://auth-service:9991/.well-known/jwks.json